version: "3.8"

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    command: mongod --port 27017
    restart: always
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ./data:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: scraper

  mongo-express:
    container_name: mongo-express
    depends_on:
      - mongo
    image: mongo-express:latest
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT}:8081
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:${MONGO_PORT}/"
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}

  scraper:
    build:
      context: .
      dockerfile: Dockerfile
      target: scraper
    container_name: scraper
    depends_on:
      - mongo
      - mongo-express
    restart: always
    environment:
      MONGODB_URI: "mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:${MONGO_PORT}/"
      MONGO_DATABASE: ${MONGO_DATABASE}

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    container_name: api
    ports:
      - ${API_PORT}:3000
    depends_on:
      - mongo
      - mongo-express
    restart: always
    environment:
      MONGODB_URI: "mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:${MONGO_PORT}/"
      MONGO_DATABASE: ${MONGO_DATABASE}
